
name: Codespaces - Validate Compose

on:
  workflow_dispatch:

jobs:
  compose-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compose config check
        run: docker compose config
